box: node
build:
  steps:
    - npm-install
    - npm-test

    - script:
        name: echo nodejs information
        code: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"

deploy:
  steps:
    - uetchy/gh-pages:
        token: $GITHUB_TOKEN
        repo: Team-Hunch/asteroids-on-steroids
        path: .
